In [ ]:
# Section A: Data Structures & Control Structures

In [4]:
#1. Create list of 5 integers and perform lists operations

# Create a list of 5 integers
numbers = [10, 20, 30, 40, 50]
print("Original list:", numbers)

# append
numbers.append(60)
print("After append:", numbers)

# extend
numbers.extend([70, 80])
print("After extend:", numbers)

# insert
numbers.insert(2, 25)
print("After insert:", numbers)

# remove
numbers.remove(40)
print("After remove:", numbers)

# pop
numbers.pop()
print("After pop:", numbers)

# index
print("Index of 30:", numbers.index(30))

# count
print("Count of 20:", numbers.count(20))

# sort
numbers.sort()
print("After sort:", numbers)

# reverse
numbers.reverse()
print("After reverse:", numbers)

# clear
numbers.clear()
print("After clear:", numbers)


Original list: [10, 20, 30, 40, 50]
After append: [10, 20, 30, 40, 50, 60]
After extend: [10, 20, 30, 40, 50, 60, 70, 80]
After insert: [10, 20, 25, 30, 40, 50, 60, 70, 80]
After remove: [10, 20, 25, 30, 50, 60, 70, 80]
After pop: [10, 20, 25, 30, 50, 60, 70]
Index of 30: 3
Count of 20: 1
After sort: [10, 20, 25, 30, 50, 60, 70]
After reverse: [70, 60, 50, 30, 25, 20, 10]
After clear: []


In [7]:
# 2.Tuple 

#create a tuple with 3students name
students = ("Sharmila" , "Kaviya" , "Hari" )
#Trying to change the first element
students[1] = "Thanshika"

#Output: It will raise a TypeError. Because Tuples are immutable(elements cannot be changed Once created). If we need to change the second value in the tuple,
#we need to change the tuple into list and actions will be perform then again change list to tuple.

TypeError: 'tuple' object does not support item assignment

In [9]:
# 3.Set with duplicates value

#create a set
Numbers = {1,2,3,4,5,2,3,4,1,0,5,6,7,8}
print(Numbers)

#Explanation: Sets automatically remove duplicate values, so each element appears only once in the output.

{0, 1, 2, 3, 4, 5, 6, 7, 8}


In [10]:
# 4.Dictionary Operations

#create dictionary
Dict = { 
    'name': 'Sharmila' ,
    'age': 21,
    'city':'Hosur'
 }

#update age
Dict['age'] = 22

#Add a new key 'email'
Dict['email'] = 'ssharmi1844@gmail.com'

#print final dictionary
print(Dict)

{'name': 'Sharmila', 'age': 22, 'city': 'Hosur', 'email': 'ssharmi1844@gmail.com'}


In [14]:
# 5.Voting eligibility check

age=int(input("Enter your age: "))

#check condition
if(age>=18):
    print("Eligible to vote")
else:
    print("Not Eligible to vote")

Enter your age:  8


Not Eligible to vote


In [16]:
# 6.Grade calculation
marks = int(input("Enter the marks: "))
if marks >= 90:
    print("Grade: A")
elif marks >= 75:
    print("Grade: B")
elif marks >= 50:
    print("Grade: C")
else:
    print("Fail")

Enter the marks:  49


Fail


In [22]:
# 7.Negative,zero,positive check

num=int(input("Enter the number: "))

if num > 0:
    print("Number is positive")
    if num % 2 == 0:
        print("It is also even")
    else:
        print("It is odd")
elif num == 0:
    print("Number is zero")
else:
    print("Number is negative")


Enter the number:  0


Number is zero


In [ ]:
# Section B: Numpy

In [30]:
# 8.Creating Scalar, 1D Array, and 2D Array

import numpy as np

#scalar
scalar = np.array(5)
print("Scalar:",scalar)

#1D Array
array_1d = np.array([1,2,3,4,5,6,7])
print("1D Array:\n",array_1d)

#2D Array
array_2d = np.array([[10,20,30],
                     [40,50,60]])
print("2D array:\n",array_2d)


Scalar: 5
1D Array:
 [1 2 3 4 5 6 7]
2D array:
 [[10 20 30]
 [40 50 60]]


In [40]:
# 9.4X4 Random Array(0,100)

import numpy as np

random_array = np.random.randint(0,101,size=(4,4))
print("4 x 4 Random Array:\n",random_array)

4 x 4 Random Array:
 [[91 27 62 17]
 [68 38 77 73]
 [19 17  2 63]
 [84 75 91 64]]


In [41]:
# 10.Convert NumPy Array to Pandas DataFrame
import numpy as np
import pandas as pd

# Create a 3x3 NumPy array
numpy_array = np.array([[10, 20, 30],
                         [40, 50, 60],
                         [70, 80, 90]])

# Convert to Pandas DataFrame with column names
df = pd.DataFrame(numpy_array, columns=['A', 'B', 'C'])

print("Pandas DataFrame:\n", df)


Pandas DataFrame:
     A   B   C
0  10  20  30
1  40  50  60
2  70  80  90


In [ ]:
#Section C: Exploring Pandas

In [65]:
# 11.Creating and Exploring a Pandas DataFrame
import numpy as np
import pandas as pd

#create dataframe manually with 10rows
data = { 
    "Name": ["Sharmila", "Anu", "Ravi", "Karthik", "Priya",
             "Anu", "Suresh", "Meena", "Rahul", "Divya"],
    "Age": [22, 24, 25, 23, 26, 24, 28, 27, 25, 23],
    "City": ["Hosur", "Bangalore", "Hyderabad", "Chennai", "Mumbai",
             "Bangalore", "Delhi", "Pune", "Hyderabad", "Chennai"],
    "Salary": [25000, 30000, np.nan, 28000, 35000,
               30000, 40000, 32000, np.nan, 27000]
       }
df = pd.DataFrame(data)
df = df.reset_index(drop=True)
df.index+=1
df

Name  Age       City   Salary
1   Sharmila   22      Hosur  25000.0
2        Anu   24  Bangalore  30000.0
3       Ravi   25  Hyderabad      NaN
4    Karthik   23    Chennai  28000.0
5      Priya   26     Mumbai  35000.0
6        Anu   24  Bangalore  30000.0
7     Suresh   28      Delhi  40000.0
8      Meena   27       Pune  32000.0
9      Rahul   25  Hyderabad      NaN
10     Divya   23    Chennai  27000.0

In [61]:
#use.info() Displays column names, data types, non-null values, and memory usage.
print("Info:\n",df.info())


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 1 to 10
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Name    10 non-null     object 
 1   Age     10 non-null     int64  
 2   City    10 non-null     object 
 3   Salary  8 non-null      float64
dtypes: float64(1), int64(1), object(2)
memory usage: 452.0+ bytes
Info:
 None


In [62]:
#use.describe() Displays count, mean, standard deviation, minimum, and maximum values for numerical columns.
print("\nDescribe:\n",df.describe())



Describe:
              Age        Salary
count  10.000000      8.000000
mean   24.700000  30875.000000
std     1.888562   4793.969426
min    22.000000  25000.000000
25%    23.250000  27750.000000
50%    24.500000  30000.000000
75%    25.750000  32750.000000
max    28.000000  40000.000000


In [63]:
#Select 'Name' and 'city' Columns
print("\nSelecting name and city:\n",df[['Name','City']])


Selecting name and city:
         Name       City
1   Sharmila      Hosur
2        Anu  Bangalore
3       Ravi  Hyderabad
4    Karthik    Chennai
5      Priya     Mumbai
6        Anu  Bangalore
7     Suresh      Delhi
8      Meena       Pune
9      Rahul  Hyderabad
10     Divya    Chennai


In [64]:
#Drop 'City' Column
print("\nDrop city:\n",df.drop('City', axis=1))


Drop city:
         Name  Age   Salary
1   Sharmila   22  25000.0
2        Anu   24  30000.0
3       Ravi   25      NaN
4    Karthik   23  28000.0
5      Priya   26  35000.0
6        Anu   24  30000.0
7     Suresh   28  40000.0
8      Meena   27  32000.0
9      Rahul   25      NaN
10     Divya   23  27000.0


In [70]:
#Fill Missing Values in 'Salary' with Mean

#find mean for salary
salary_mean = df['Salary'].mean()

#fill the missing value with mean value
df['Salary'] = df['Salary'].fillna(salary_mean)

print("\nAfter Filling Missing Salary Values:\n", df)




After Filling Missing Salary Values:
         Name  Age       City   Salary
1   Sharmila   22      Hosur  25000.0
2        Anu   24  Bangalore  30000.0
3       Ravi   25  Hyderabad  30875.0
4    Karthik   23    Chennai  28000.0
5      Priya   26     Mumbai  35000.0
7     Suresh   28      Delhi  40000.0
8      Meena   27       Pune  32000.0
9      Rahul   25  Hyderabad  30875.0
10     Divya   23    Chennai  27000.0


C:\Users\ADMIN\AppData\Local\Temp\ipykernel_11820\1504344048.py:7: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Salary'] = df['Salary'].fillna(salary_mean)


In [67]:
#Remove Duplicate Rows
df = df.drop_duplicates()
print("\nAfter Removing Duplicate Rows:\n", df)



After Removing Duplicate Rows:
         Name  Age       City   Salary
1   Sharmila   22      Hosur  25000.0
2        Anu   24  Bangalore  30000.0
3       Ravi   25  Hyderabad  30875.0
4    Karthik   23    Chennai  28000.0
5      Priya   26     Mumbai  35000.0
7     Suresh   28      Delhi  40000.0
8      Meena   27       Pune  32000.0
9      Rahul   25  Hyderabad  30875.0
10     Divya   23    Chennai  27000.0
